services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=webhook.dummy.de
      - VALIDATION=http
      - STAGING=true #for testing set to true
      - SWAG_AUTORELOAD=true
    volumes:
      - /srv/proxy/config:/config
    ports:
      - 0.0.0.0:443:443
      - 0.0.0.0:80:80
    networks:
      - proxy
    restart: unless-stopped
  privileges-server:
    image: ghcr.io/mr-nordsee/macos-privlog:latest
    container_name: webhook
    volumes:
      - /srv/proxy/priv/Data:/app/Data
      - /srv/proxy/priv/Logs:/app/Logs
      - /srv/proxy/priv/backup:/app/backup
    restart: unless-stopped
    environment:
      API_KEYS: /run/secrets/api_keys
      BACKUP_RETENTION_DAYS: 20 #Optional
      DATABASE_RETENTION_DAYS: 30 #Optional
      LOG_LEVEL: DEBUG #Optional
      LOGFILE_RETENTION_DAYS: 7 #Optional
      DB_BACKUP_CRONJOB: "10 0 * * *" #Optional
      HEALTH_OUTPUT_DISKSPACE: True #Optional
    networks:
      - proxy
    secrets:
      - api_keys

networks:
  proxy:
    driver: bridge

secrets:
  api_keys:
    file: ./secrets/api_keys.txt